# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets

platforms_dir = os.path.join(os.path.dirname(__file__), '..', 'platforms')
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = platforms_dir
if hasattr(QtCore, 'QCoreApplication'):
    QtCore.QCoreApplication.addLibraryPath(platforms_dir)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_main_title.setFont(font)
        self.label_main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_title.setObjectName("label_main_title")
        self.verticalLayout.addWidget(self.label_main_title)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        
        self.tab_caesar = self.create_cipher_tab("caesar", "Caesar")
        self.tabWidget.addTab(self.tab_caesar, "Caesar")
        self.tab_vigenere = self.create_cipher_tab("vigenere", "Vigenère")
        self.tabWidget.addTab(self.tab_vigenere, "Vigenère")
        self.tab_railfence = self.create_cipher_tab("railfence", "Rail Fence")
        self.tabWidget.addTab(self.tab_railfence, "Rail Fence")
        self.tab_playfair = self.create_cipher_tab("playfair", "Playfair")
        self.tabWidget.addTab(self.tab_playfair, "Playfair")
        self.tab_transposition = self.create_cipher_tab("transposition", "Transposition")
        self.tabWidget.addTab(self.tab_transposition, "Transposition")

        self.tab_rsa = self.create_rsa_tab()
        self.tabWidget.addTab(self.tab_rsa, "RSA")
        self.tab_ecc = self.create_ecc_tab()
        self.tabWidget.addTab(self.tab_ecc, "ECC")

        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def create_cipher_tab(self, name, title):
        tab = QtWidgets.QWidget()
        tab.setObjectName(f"tab_{name}")
        gridLayout = QtWidgets.QGridLayout(tab)
        gridLayout.setObjectName(f"gridLayout_{name}")
        label_plain = QtWidgets.QLabel(f"Văn bản gốc (Plaintext):", tab)
        gridLayout.addWidget(label_plain, 0, 0, 1, 1)
        text_edit_plain = QtWidgets.QTextEdit(tab)
        gridLayout.addWidget(text_edit_plain, 1, 0, 1, 2)
        label_key = QtWidgets.QLabel("Khóa (Key):", tab)
        gridLayout.addWidget(label_key, 2, 0, 1, 1)
        line_edit_key = QtWidgets.QLineEdit(tab)
        gridLayout.addWidget(line_edit_key, 2, 1, 1, 1)
        label_cipher = QtWidgets.QLabel("Văn bản mã hóa (Ciphertext):", tab)
        gridLayout.addWidget(label_cipher, 3, 0, 1, 1)
        text_edit_cipher = QtWidgets.QTextEdit(tab)
        gridLayout.addWidget(text_edit_cipher, 4, 0, 1, 2)
        button_encrypt = QtWidgets.QPushButton(f"Mã hóa {title}", tab)
        gridLayout.addWidget(button_encrypt, 5, 0, 1, 1)
        button_decrypt = QtWidgets.QPushButton(f"Giải mã {title}", tab)
        gridLayout.addWidget(button_decrypt, 5, 1, 1, 1)
        
        setattr(self, f"{name}_text_plain", text_edit_plain)
        setattr(self, f"{name}_line_key", line_edit_key)
        setattr(self, f"{name}_text_cipher", text_edit_cipher)
        setattr(self, f"{name}_btn_encrypt", button_encrypt)
        setattr(self, f"{name}_btn_decrypt", button_decrypt)
        
        return tab

    def create_rsa_tab(self):
        tab = QtWidgets.QWidget()
        gridLayout = QtWidgets.QGridLayout(tab)
        self.rsa_btn_gen_keys = QtWidgets.QPushButton("Tạo cặp khóa mới (RSA 2048-bit)", tab)
        gridLayout.addWidget(self.rsa_btn_gen_keys, 0, 0, 1, 2)
        groupBox_encrypt_decrypt = QtWidgets.QGroupBox("Mã hóa & Giải mã", tab)
        gridLayout_ed = QtWidgets.QGridLayout(groupBox_encrypt_decrypt)
        label_plain = QtWidgets.QLabel("Văn bản gốc:", groupBox_encrypt_decrypt)
        self.rsa_text_plain = QtWidgets.QTextEdit(groupBox_encrypt_decrypt)
        gridLayout_ed.addWidget(label_plain, 0, 0, 1, 1)
        gridLayout_ed.addWidget(self.rsa_text_plain, 1, 0, 1, 2)
        label_cipher = QtWidgets.QLabel("Văn bản mã hóa (dạng Hex):", groupBox_encrypt_decrypt)
        self.rsa_text_cipher = QtWidgets.QTextEdit(groupBox_encrypt_decrypt)
        gridLayout_ed.addWidget(label_cipher, 2, 0, 1, 1)
        gridLayout_ed.addWidget(self.rsa_text_cipher, 3, 0, 1, 2)
        self.rsa_btn_encrypt = QtWidgets.QPushButton("Mã hóa (với Public Key)", groupBox_encrypt_decrypt)
        self.rsa_btn_decrypt = QtWidgets.QPushButton("Giải mã (với Private Key)", groupBox_encrypt_decrypt)
        gridLayout_ed.addWidget(self.rsa_btn_encrypt, 4, 0, 1, 1)
        gridLayout_ed.addWidget(self.rsa_btn_decrypt, 4, 1, 1, 1)
        gridLayout.addWidget(groupBox_encrypt_decrypt, 1, 0, 1, 1)
        groupBox_sign_verify = QtWidgets.QGroupBox("Ký & Xác thực", tab)
        gridLayout_sv = QtWidgets.QGridLayout(groupBox_sign_verify)
        label_info = QtWidgets.QLabel("Thông điệp:", groupBox_sign_verify)
        self.rsa_text_info = QtWidgets.QTextEdit(groupBox_sign_verify)
        gridLayout_sv.addWidget(label_info, 0, 0, 1, 1)
        gridLayout_sv.addWidget(self.rsa_text_info, 1, 0, 1, 2)
        label_sign = QtWidgets.QLabel("Chữ ký (dạng Hex):", groupBox_sign_verify)
        self.rsa_text_sign = QtWidgets.QTextEdit(groupBox_sign_verify)
        gridLayout_sv.addWidget(label_sign, 2, 0, 1, 1)
        gridLayout_sv.addWidget(self.rsa_text_sign, 3, 0, 1, 2)
        self.rsa_btn_sign = QtWidgets.QPushButton("Ký (với Private Key)", groupBox_sign_verify)
        self.rsa_btn_verify = QtWidgets.QPushButton("Xác thực (với Public Key)", groupBox_sign_verify)
        gridLayout_sv.addWidget(self.rsa_btn_sign, 4, 0, 1, 1)
        gridLayout_sv.addWidget(self.rsa_btn_verify, 4, 1, 1, 1)
        gridLayout.addWidget(groupBox_sign_verify, 1, 1, 1, 1)
        
        return tab

    def create_ecc_tab(self):
        tab = QtWidgets.QWidget()
        tab.setObjectName("tab_ecc")
        gridLayout = QtWidgets.QGridLayout(tab)
        self.ecc_btn_gen_keys = QtWidgets.QPushButton("Tạo cặp khóa mới (ECC NIST256p)", tab)
        gridLayout.addWidget(self.ecc_btn_gen_keys, 0, 0, 1, 1)
        groupBox_sign_verify = QtWidgets.QGroupBox("Ký & Xác thực bằng ECC", tab)
        gridLayout_sv = QtWidgets.QGridLayout(groupBox_sign_verify)
        label_info = QtWidgets.QLabel("Thông điệp:", groupBox_sign_verify)
        self.ecc_text_info = QtWidgets.QTextEdit(groupBox_sign_verify)
        gridLayout_sv.addWidget(label_info, 0, 0, 1, 1)
        gridLayout_sv.addWidget(self.ecc_text_info, 1, 0, 1, 2)
        label_sign = QtWidgets.QLabel("Chữ ký (dạng Hex):", groupBox_sign_verify)
        self.ecc_text_sign = QtWidgets.QTextEdit(groupBox_sign_verify)
        gridLayout_sv.addWidget(label_sign, 2, 0, 1, 1)
        gridLayout_sv.addWidget(self.ecc_text_sign, 3, 0, 1, 2)
        
        self.ecc_btn_sign = QtWidgets.QPushButton("Ký (với Private Key)", groupBox_sign_verify)
        self.ecc_btn_verify = QtWidgets.QPushButton("Xác thực (với Public Key)", groupBox_sign_verify)
        gridLayout_sv.addWidget(self.ecc_btn_sign, 4, 0, 1, 1)
        gridLayout_sv.addWidget(self.ecc_btn_verify, 4, 1, 1, 1)
        gridLayout.addWidget(groupBox_sign_verify, 1, 0, 1, 1)
        
        return tab

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Công Cụ Mã Hóa"))
        self.label_main_title.setText(_translate("MainWindow", "BẢO MẬT THÔNG TIN NÂNG CAO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_caesar), _translate("MainWindow", "Caesar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vigenere), _translate("MainWindow", "Vigenère"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_railfence), _translate("MainWindow", "Rail Fence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_playfair), _translate("MainWindow", "Playfair"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_transposition), _translate("MainWindow", "Transposition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rsa), _translate("MainWindow", "RSA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ecc), _translate("MainWindow", "ECC"))
